### ISSUE TITLE
Binding problems with delimiters (e.g. upper/camel case)

### ISSUE THREAD

**Issue by BairDev** [canjs/can-attribute-encoder#11]
I've stumbled upon an issue while debugging a not working binding for a child component.
The code (stache) looked like this: `<my-comp vm:sProperty:to="sSomeKey" />`

Suppose, that all attributes (sProperty and sSomeKey) do exist in the view models and everything is wired together correctly. Firstly I've noticed, that the binding did not work, so `sProperty`in the child component (<my-comp>) was updated at some point, but not the one (`sSomeKey`) in the parent compenent. Then I realized that the attribute has somehow become `vm: u:property:to="sSomeKey"`.

I went on with debugging and found the issue in this [line of code](https://github.com/canjs/can-attribute-encoder/blob/73fbd0692ce4bb42eb60a0bc849e2c3503e9cdd3/can-attribute-encoder.js#L109), where the upper case `P` is replaced by `:u:p`, which leads to the expression `vm:s:u:property`, which is *probably* reverted later to the one with the space, because `:s:` is a delimiter for a space.

So this leads to unintended consequences I'd say and I would at least update the documentation (especially [this one and its children](https://canjs.com/doc/can-stache-bindings.html)), but it seems also to be good to think about the handling of attributes in camel case.

**Comment by justinbmeyer** [comment]
Good catch. We should be able to fix this today or tomorrow.
