### ISSUE TITLE
Encode/decode :raw bindings

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-attribute-encoder#21]
Right now, `encode("nameProp:raw")` returns `"nameProp:raw"` when I think it should return `"name:u:prop:raw"`.

I think support for `:raw` needs to be added to `encode`: https://github.com/canjs/can-attribute-encoder/blob/44a00dc0732e5675688af6425809f2223d8cb73c/can-attribute-encoder.js#L105-L106

…and `decode`: https://github.com/canjs/can-attribute-encoder/blob/44a00dc0732e5675688af6425809f2223d8cb73c/can-attribute-encoder.js#L165

This came up because of a question @pYr0x asked on Gitter: https://gitter.im/canjs/canjs?at=5af0bb0459a0578004b08c89

**Comment by m-mujica** [comment]
@pYr0x had to take this one from you, hope you don't mind ;)
